# Generated by Django 4.1.6 on 2023-10-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_location', models.CharField(db_column='location', max_length=30)),
                ('min_temp', models.FloatField(db_column='min_temp')),
                ('max_temp', models.FloatField(db_column='max_temp')),
                ('email', models.EmailField(db_column='Email', max_length=254)),
            ],
        ),
    ]
