# Generated by Django 4.1.6 on 2023-10-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuWeDetector', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
